name: vitap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.81
  - blast=2.5
  - boost=1.83
  - bzip2=1.0
  - ca-certificates=2023.11.17
  - colorama=0.4
  - diamond=0.9
  - entrez-direct=16.2
  - gettext=0.21
  - icu=73.2
  - ld_impl_linux-64=2.40
  - libblas=3.9
  - libboost=1.83
  - libboost-devel=1.83
  - libboost-headers=1.83
  - libboost-python=1.83
  - libboost-python-devel=1.83
  - libcblas=3.9
  - libexpat=2.5
  - libffi=3.4
  - libgcc-ng=13.2
  - libgfortran-ng=13.2
  - libgfortran5=13.2
  - libgomp=13.2
  - libidn2=2.3
  - liblapack=3.9
  - libnsl=2.0
  - libopenblas=0.3
  - libsqlite=3.44
  - libstdcxx-ng=13.2
  - libunistring=0.9
  - libuuid=2.38
  - libzlib=1.2
  - ncurses=6.4
  - networkx=3.2
  - numpy=1.26
  - openssl=3.2
  - pandas=2.1
  - pip=23.3
  - prodigal-gv=2.6
  - python=3.12
  - python-dateutil=2.8
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - readline=8.2
  - seqkit=2.6
  - setuptools=68.2
  - six=1.16
  - tk=8.6
  - tqdm=4.66
  - tzdata=2023c
  - wget=1.20
  - wheel=0.42
  - xz=5.2
  - zlib=1.2
  - zstd=1.5
prefix: /lustre/home/wangmin/miniconda3/envs/vitap
